In [ ]:
arr[4][2] = { 1, 0, -1, 0, 0, 1, 0, -1 }

In [86]:
import numpy as np
M = np.array([[1,1,0,0],[1,1,0,0],[0,0,0,1],[0,0,0,1]])
mx,my = M.shape
mx -= 1
my -= 1
ex = 2
ey = 3
num = 0
Min = 99999
def dfs(x, y, num):
    print((x,y),num)
    if (x==ex and y==ey):
        print(11111)
        if num < Min:
            Min = num
        return Min
    for rx,ry in [[x,y-1],[x,y+1], [x-1,y], [x+1,y]]: #4个方向
        #print('Ms:',rx,ry,M[rx,ry])
        if rx<0 or rx>mx or ry<0 or ry>my or  M[rx,ry]==2 : #边界跳过
            print('con')
            continue
        tmp = M[rx,ry] 
        if tmp == 0:
            num += 1
        M[x,y] = 2
        print(M)
        print('----------------------------')
        dfs(rx,ry, num)
        M[rx,ry] = tmp
dd = bfs(0, 0, 0)
print(Min)

(0, 0) 0
con
[[2 1 0 0]
 [1 1 0 0]
 [0 0 0 1]
 [0 0 0 1]]
----------------------------
(0, 1) 0
con
[[2 2 0 0]
 [1 1 0 0]
 [0 0 0 1]
 [0 0 0 1]]
----------------------------
(0, 2) 1
con
[[2 2 2 0]
 [1 1 0 0]
 [0 0 0 1]
 [0 0 0 1]]
----------------------------
(0, 3) 2
con
con
con
[[2 2 2 2]
 [1 1 0 0]
 [0 0 0 1]
 [0 0 0 1]]
----------------------------
(1, 3) 3
[[2 2 2 2]
 [1 1 0 2]
 [0 0 0 1]
 [0 0 0 1]]
----------------------------
(1, 2) 4
[[2 2 2 2]
 [1 1 2 2]
 [0 0 0 1]
 [0 0 0 1]]
----------------------------
(1, 1) 4
[[2 2 2 2]
 [1 2 2 2]
 [0 0 0 1]
 [0 0 0 1]]
----------------------------
(1, 0) 4
con
con
con
[[2 2 2 2]
 [2 2 2 2]
 [0 0 0 1]
 [0 0 0 1]]
----------------------------
(2, 0) 5
con
[[2 2 2 2]
 [2 2 2 2]
 [2 0 0 1]
 [0 0 0 1]]
----------------------------
(2, 1) 6
con
[[2 2 2 2]
 [2 2 2 2]
 [2 2 0 1]
 [0 0 0 1]]
----------------------------
(2, 2) 7
con
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 1]
 [0 0 0 1]]
----------------------------
(2, 3) 7
11111


UnboundLocalError: local variable 'Min' referenced before assignment

In [7]:
import numpy as np
M = np.array([[1,1,0,0],[1,1,0,0],[0,0,0,1],[0,0,0,1]])
mx,my = M.shape
mx -= 1
my -= 1
ex = 2
ey = 3
num = 0
Min = 99999
def bfs(x, y, num):
    print((x,y),num)
    if (x==ex and y==ey):
        print(11111)
        if num < Min:
            Min = num
        return Min
    for rx,ry in [[x,y-1],[x,y+1], [x-1,y], [x+1,y]]: #4个方向
        #print('Ms:',rx,ry,M[rx,ry])
        if rx<0 or rx>mx or ry<0 or ry>my or  M[rx,ry]==2 : #边界跳过
            print('con')
            continue
        tmp = M[rx,ry] 
        if tmp == 0:
            num += 1
        M[x,y] = 2
        print(M)
        print('----------------------------')
        bfs(rx,ry, num)
        M[rx,ry] = tmp
        
        
    
dd = bfs(0, 0, 0)
print(Min)